# ===================================================================
# MCP Multi-Agent System - Configuration Test
# ===================================================================
# Tests Perplexity AI + GitHub Copilot integration
# Author: Auto-generated by MCP setup
# Date: 2025-10-28
# ===================================================================

Write-Host "`n=====================================" -ForegroundColor Cyan
Write-Host "  MCP Multi-Agent System Test" -ForegroundColor Cyan
Write-Host "=====================================" -ForegroundColor Cyan

# Check 1: Environment Variables
Write-Host "`n[1/5] Checking environment variables..." -ForegroundColor Yellow

$env_file = ".env"
if (Test-Path $env_file) {
    Write-Host "  [OK] .env file exists" -ForegroundColor Green
    
    # Load .env
    Get-Content $env_file | ForEach-Object {
        if ($_ -match '^([^#][^=]+)=(.*)$') {
            $key = $matches[1].Trim()
            $value = $matches[2].Trim()
            [Environment]::SetEnvironmentVariable($key, $value, "Process")
        }
    }
    
    # Check PERPLEXITY_API_KEY
    if ($env:PERPLEXITY_API_KEY -and $env:PERPLEXITY_API_KEY -ne "pplx-your-api-key-here") {
        Write-Host "  [OK] PERPLEXITY_API_KEY configured" -ForegroundColor Green
    } else {
        Write-Host "  [FAIL] PERPLEXITY_API_KEY missing or not configured" -ForegroundColor Red
    }
    
    # Check GITHUB_TOKEN
    if ($env:GITHUB_TOKEN -and $env:GITHUB_TOKEN -ne "YOUR_GITHUB_TOKEN_HERE") {
        Write-Host "  [OK] GITHUB_TOKEN configured" -ForegroundColor Green
    } else {
        Write-Host "  [FAIL] GITHUB_TOKEN missing or not configured" -ForegroundColor Red
    }
} else {
    Write-Host "  [FAIL] .env file not found!" -ForegroundColor Red
    Write-Host "    Copy .env.example to .env and configure your API keys" -ForegroundColor Yellow
}

# Check 2: MCP Configuration
Write-Host "`n[2/5] Checking MCP configuration..." -ForegroundColor Yellow

$mcp_config = ".vscode\mcp.json"
if (Test-Path $mcp_config) {
    Write-Host "  [OK] .vscode\mcp.json exists" -ForegroundColor Green
    
    $config = Get-Content $mcp_config -Raw | ConvertFrom-Json
    
    # Check Perplexity server
    if ($config.servers.Perplexity) {
        Write-Host "  [OK] Perplexity server configured" -ForegroundColor Green
        Write-Host "    Type: $($config.servers.Perplexity.type)" -ForegroundColor Gray
        Write-Host "    Command: $($config.servers.Perplexity.command)" -ForegroundColor Gray
    } else {
        Write-Host "  [FAIL] Perplexity server not found in config" -ForegroundColor Red
    }
    
    # Check GitHubCopilot
    if ($config.servers.GitHubCopilot) {
        Write-Host "  [OK] GitHubCopilot configured" -ForegroundColor Green
        Write-Host "    Enabled: $($config.servers.GitHubCopilot.enabled)" -ForegroundColor Gray
    } else {
        Write-Host "  [FAIL] GitHubCopilot not found in config" -ForegroundColor Red
    }
    
    # Check workflow
    if ($config.workflow) {
        Write-Host "  [OK] Workflow routing configured" -ForegroundColor Green
        Write-Host "    Task Management: $($config.workflow.taskManagement)" -ForegroundColor Gray
        Write-Host "    Research: $($config.workflow.research)" -ForegroundColor Gray
        Write-Host "    Solution Execution: $($config.workflow.solutionExecution -join ', ')" -ForegroundColor Gray
    } else {
        Write-Host "  [FAIL] Workflow routing not configured" -ForegroundColor Red
    }
} else {
    Write-Host "  [FAIL] .vscode\mcp.json not found!" -ForegroundColor Red
}

# Check 3: Node.js and NPM
Write-Host "`n[3/5] Checking Node.js environment..." -ForegroundColor Yellow

try {
    $node_version = node --version 2>&1
    Write-Host "  [OK] Node.js installed: $node_version" -ForegroundColor Green
    
    # Check version >= 16
    $version_number = [int]($node_version -replace 'v(\d+)\..*', '$1')
    if ($version_number -ge 16) {
        Write-Host "  [OK] Node.js version >= 16 (required)" -ForegroundColor Green
    } else {
        Write-Host "  [FAIL] Node.js version too old (please upgrade to v16+)" -ForegroundColor Red
    }
} catch {
    Write-Host "  [FAIL] Node.js not found!" -ForegroundColor Red
    Write-Host "    Install from: https://nodejs.org/" -ForegroundColor Yellow
}

try {
    $npm_version = npm --version 2>&1
    Write-Host "  [OK] npm installed: $npm_version" -ForegroundColor Green
} catch {
    Write-Host "  [FAIL] npm not found!" -ForegroundColor Red
}

# Check 4: MCP Server Packages
Write-Host "`n[4/5] Checking MCP server packages..." -ForegroundColor Yellow

$packages = @(
    "@modelcontextprotocol/server-perplexity-ask",
    "@modelcontextprotocol/server-github",
    "@modelcontextprotocol/server-filesystem"
)

foreach ($package in $packages) {
    try {
        $check = npm list -g $package 2>&1
        if ($LASTEXITCODE -eq 0) {
            Write-Host "  [OK] $package installed globally" -ForegroundColor Green
        } else {
            Write-Host "  [WARN] $package not installed globally" -ForegroundColor Yellow
            Write-Host "    Will be installed on first use via npx" -ForegroundColor Gray
        }
    } catch {
        Write-Host "  [WARN] Cannot check $package (will auto-install)" -ForegroundColor Yellow
    }
}

# Check 5: VS Code Extension
Write-Host "`n[5/5] Checking VS Code setup..." -ForegroundColor Yellow

if (Test-Path ".vscode\settings.json") {
    Write-Host "  [OK] VS Code settings.json exists" -ForegroundColor Green
} else {
    Write-Host "  [WARN] VS Code settings.json not found" -ForegroundColor Yellow
}

if (Test-Path ".vscode\MULTI_AGENT_SETUP.md") {
    Write-Host "  [OK] MCP documentation exists" -ForegroundColor Green
} else {
    Write-Host "  [WARN] MCP documentation not found" -ForegroundColor Yellow
}

# Summary
Write-Host "`n=====================================" -ForegroundColor Cyan
Write-Host "  Test Summary" -ForegroundColor Cyan
Write-Host "=====================================" -ForegroundColor Cyan

Write-Host "`nNext steps:" -ForegroundColor Yellow
Write-Host "  1. Restart VS Code to load MCP configuration" -ForegroundColor White
Write-Host "  2. MCP servers will auto-start on VS Code launch" -ForegroundColor White
Write-Host "  3. Test with: @perplexity What is MCP?" -ForegroundColor White
Write-Host "  4. Read .vscode\MULTI_AGENT_SETUP.md for examples" -ForegroundColor White

Write-Host "`nMCP Status Check:" -ForegroundColor Yellow
Write-Host "  Open VS Code Command Palette (Ctrl+Shift+P)" -ForegroundColor White
Write-Host "  Run: 'MCP: Show Server Status'" -ForegroundColor White

Write-Host "`n=====================================" -ForegroundColor Cyan
Write-Host "Done! Happy coding with AI agents! 🤖" -ForegroundColor Green
Write-Host "=====================================" -ForegroundColor Cyan
